version: 2.1

orbs:
  win: circleci/windows@5.1

jobs:
  build-linux:
    docker:
      - image: cimg/base:2025.10
    resource_class: large
    environment:
      NUMBER_OF_CPUS: 4
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install g++ clang git make libgtk-3-dev libnotify-dev libbz2-dev libssl-dev xdotool
      - run: ./configure
      - run: make -f Makefile -j ${NUMBER_OF_CPUS}
      - run: make -f umkMakefile -j ${NUMBER_OF_CPUS}
  build-mac:
    macos:
      xcode: 26.2.0
    resource_class: m4pro.medium
    environment:
      NUMBER_OF_CPUS: 4
    steps:
      - checkout
      - run: ./configure
      - run: make -f umkMakefile -j ${NUMBER_OF_CPUS}
      - run: ./umk ./uppsrc ide CLANG -brs ./theide
  build-windows:
    executor: win/default
    steps:
      - checkout
      - run: New-Item -Path "3p\downloads" -ItemType Directory -Force
      - run: curl.exe -L -o "3p\downloads\umk.7z" "https://github.com/ultimatepp/ultimatepp/releases/download/v2025.1.1/umk-win-17810.7z"
      - run: 7z x 3p\downloads\umk.7z -o3p
      - run: 3p\umk\umk ./uppsrc ide 3p\umk\CLANG.bm -brs +GUI ./theide
      - run: 3p\umk\umk ./uppsrc umk 3p\umk\CLANG.bm -brs ./umk

workflows:
  build-linux:
    jobs:
      - build-linux
  
  build-mac:
    jobs:
      - build-mac

  build-windows:
    jobs:
      - build-windows
